import { Deal } from "@/components/DealCard";

export const deals: Deal[] = [
  {
    id: "lhr-jfk-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "New York",
    toCode: "JFK",
    price: 299,
    currency: "£",
    normalPrice: 520,
    cabin: "Economy",
    airline: "BA",
    duration: "8.2h",
    stops: 0,
    availability: "Mar–Aug 2026",
    tags: ["cheap", "directish", "americas"],
  },
  {
    id: "lgw-lax-economy",
    from: "London, UK",
    fromCode: "LGW",
    to: "Los Angeles",
    toCode: "LAX",
    price: 389,
    currency: "£",
    normalPrice: 680,
    cabin: "Economy",
    airline: "Norse",
    duration: "12.6h",
    stops: 0,
    availability: "Mar–Aug 2026",
    tags: ["cheap", "directish", "americas"],
  },
  {
    id: "lhr-hnd-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Tokyo",
    toCode: "HND",
    price: 529,
    currency: "£",
    normalPrice: 890,
    cabin: "Economy",
    airline: "JAL",
    duration: "15h",
    stops: 0,
    availability: "Mar–Sep 2026",
    tags: ["cheap", "directish", "asia"],
  },
  {
    id: "lhr-bkk-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Bangkok",
    toCode: "BKK",
    price: 449,
    currency: "£",
    normalPrice: 720,
    cabin: "Economy",
    airline: "Thai",
    duration: "14.1h",
    stops: 0,
    availability: "Apr–Aug 2026",
    tags: ["cheap", "directish", "asia"],
  },
  {
    id: "lhr-dxb-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Dubai",
    toCode: "DXB",
    price: 279,
    currency: "£",
    normalPrice: 480,
    cabin: "Economy",
    airline: "BA",
    duration: "6.5h",
    stops: 0,
    availability: "Mar–Oct 2026",
    tags: ["cheap", "directish", "mena"],
  },
  {
    id: "lhr-sin-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Singapore",
    toCode: "SIN",
    price: 499,
    currency: "£",
    normalPrice: 850,
    cabin: "Economy",
    airline: "Singapore Airlines",
    duration: "13h",
    stops: 0,
    availability: "Apr–Sep 2026",
    tags: ["cheap", "directish", "asia"],
  },
  {
    id: "lhr-nbo-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Nairobi",
    toCode: "NBO",
    price: 399,
    currency: "£",
    normalPrice: 650,
    cabin: "Economy",
    airline: "Kenya Airways",
    duration: "8.6h",
    stops: 0,
    availability: "Apr–Nov 2026",
    tags: ["cheap", "directish", "africa"],
  },
  {
    id: "lhr-lim-economy",
    from: "London, UK",
    fromCode: "LHR",
    to: "Lima",
    toCode: "LIM",
    price: 599,
    currency: "£",
    normalPrice: 980,
    cabin: "Economy",
    airline: "Iberia",
    duration: "21.1h",
    stops: 1,
    availability: "Apr–Sep 2026",
    tags: ["cheap", "connection", "americas"],
  },
];
